/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.awt.Image;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.HumanResource;
import model.HumanResourceHistory;
import java.util.ArrayList;
import javax.swing.ImageIcon;

/**
 *
 * @author hp
 */

public class SearchEmpJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SearchEmpJPanel
     */
    HumanResourceHistory history;
    public SearchEmpJPanel(HumanResourceHistory history) {
        initComponents();
        
        this.history = history;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        btnView = new javax.swing.JButton();
        lblColName = new javax.swing.JLabel();
        txtColName = new javax.swing.JTextField();
        lblSearchValue = new javax.swing.JLabel();
        txtSearchValue = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        lblSearchInstr = new javax.swing.JLabel();
        lblEmpGender = new javax.swing.JLabel();
        txtEmpLevel = new javax.swing.JTextField();
        txtEmpFullName = new javax.swing.JTextField();
        lblEmpPosTitle = new javax.swing.JLabel();
        lblEmpId = new javax.swing.JLabel();
        txtEmpPhoneNo = new javax.swing.JTextField();
        txtEmpId = new javax.swing.JTextField();
        lblEmpEmail = new javax.swing.JLabel();
        lblEmpFullName = new javax.swing.JLabel();
        txtEmpEmail = new javax.swing.JTextField();
        txtEmpAge = new javax.swing.JTextField();
        txtEmpTeamInfo = new javax.swing.JTextField();
        lblEmpPhoneNo = new javax.swing.JLabel();
        txtEmpGender = new javax.swing.JTextField();
        lblEmpAge = new javax.swing.JLabel();
        lblEmpTeamInfo = new javax.swing.JLabel();
        lblEmpStartDate = new javax.swing.JLabel();
        txtEmpPosTitle = new javax.swing.JTextField();
        txtEmpStartDate = new javax.swing.JTextField();
        lblEmpLevel = new javax.swing.JLabel();
        lblImageShow = new javax.swing.JLabel();
        lblImageShowPath = new javax.swing.JLabel();
        btnClearDetails = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblEmpDetails = new javax.swing.JTable();

        setMaximumSize(new java.awt.Dimension(900, 700));
        setMinimumSize(new java.awt.Dimension(900, 700));
        setPreferredSize(new java.awt.Dimension(900, 700));

        lblTitle.setFont(new java.awt.Font("Calibri", 3, 36)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Search an Employee");

        btnView.setText("View");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        lblColName.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        lblColName.setText("Column Name:");

        lblSearchValue.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        lblSearchValue.setText("Search Value:");

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        lblSearchInstr.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lblSearchInstr.setText("Note: For Searching the Employee, The Column Name should \"Name, Id, Age, Gender, Start date, Level, Team info, Title, Phone no & Email");

        lblEmpGender.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        lblEmpGender.setText("Gender:");

        txtEmpLevel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        txtEmpFullName.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        lblEmpPosTitle.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        lblEmpPosTitle.setText("Position Title:");

        lblEmpId.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        lblEmpId.setText("Employee ID:");

        txtEmpPhoneNo.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        txtEmpId.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        lblEmpEmail.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        lblEmpEmail.setText("Email:");

        lblEmpFullName.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        lblEmpFullName.setText("Full Name:");

        txtEmpEmail.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        txtEmpAge.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        txtEmpTeamInfo.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        lblEmpPhoneNo.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        lblEmpPhoneNo.setText("Phone Number:");

        txtEmpGender.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        lblEmpAge.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        lblEmpAge.setText("Age:");

        lblEmpTeamInfo.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        lblEmpTeamInfo.setText("Team Info:");

        lblEmpStartDate.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        lblEmpStartDate.setText("Start Date:");

        txtEmpPosTitle.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        txtEmpStartDate.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        lblEmpLevel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        lblEmpLevel.setText("Level:");

        btnClearDetails.setText("Clear");
        btnClearDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearDetailsActionPerformed(evt);
            }
        });

        tblEmpDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Employee Name", "Employee ID", "Age", "Gender", "Start Date", "Level", "Team Info", "Title", "Phone No", "Email"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblEmpDetails);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblImageShowPath, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(347, 347, 347)
                                .addComponent(btnView)
                                .addGap(18, 18, 18)
                                .addComponent(btnClearDetails))
                            .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblSearchInstr, javax.swing.GroupLayout.PREFERRED_SIZE, 1046, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblColName)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtColName, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblSearchValue)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtSearchValue, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(33, 33, 33)
                                        .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblEmpId)
                                    .addComponent(lblEmpFullName)
                                    .addComponent(lblEmpAge)
                                    .addComponent(lblEmpGender)
                                    .addComponent(lblEmpStartDate))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtEmpGender, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtEmpId, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtEmpFullName, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtEmpStartDate, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtEmpAge, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblEmpLevel, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblEmpTeamInfo, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblEmpPhoneNo, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblEmpEmail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblEmpPosTitle, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtEmpPhoneNo, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtEmpPosTitle, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtEmpTeamInfo, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtEmpLevel, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtEmpEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(lblImageShow, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblColName, lblSearchValue});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblSearchInstr)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblColName)
                    .addComponent(txtColName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSearchValue)
                    .addComponent(txtSearchValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch))
                .addGap(33, 33, 33)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnView)
                    .addComponent(btnClearDetails))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblImageShow, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEmpFullName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEmpFullName))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEmpId)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(txtEmpId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(7, 7, 7)))
                        .addComponent(lblEmpAge)
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEmpGender)
                            .addComponent(txtEmpGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEmpStartDate)
                            .addComponent(txtEmpStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEmpLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEmpLevel))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEmpTeamInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEmpTeamInfo))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEmpPosTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEmpPosTitle)
                            .addComponent(txtEmpAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEmpPhoneNo)
                            .addComponent(txtEmpPhoneNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEmpEmail)
                            .addComponent(txtEmpEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(115, 115, 115)
                .addComponent(lblImageShowPath)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lblColName, lblSearchInstr, lblSearchValue});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnSearch, txtColName, txtSearchValue});

    }// </editor-fold>//GEN-END:initComponents

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:
        int rowIndexPoint = tblEmpDetails.getSelectedRow();

        if(rowIndexPoint == -1) {
            JOptionPane.showMessageDialog(this, "To view a row, please choose one!!");
            return;

        }

        DefaultTableModel model = (DefaultTableModel) tblEmpDetails.getModel();
        HumanResource empDetailsSelected = (HumanResource)model.getValueAt(rowIndexPoint, 0);

        txtEmpFullName.setText(empDetailsSelected.getEmpFullName());
        txtEmpId.setText(String.valueOf(empDetailsSelected.getEmpId()));
        txtEmpAge.setText(String.valueOf(empDetailsSelected.getEmpAge()));
        txtEmpGender.setText(empDetailsSelected.getEmpGender());
        txtEmpStartDate.setText(empDetailsSelected.getEmpStartDate());
        txtEmpLevel.setText(empDetailsSelected.getEmpLevel());
        txtEmpTeamInfo.setText(empDetailsSelected.getEmpTeamInfo());
        txtEmpPosTitle.setText(empDetailsSelected.getEmpTitle());
        txtEmpPhoneNo.setText(empDetailsSelected.getEmpPhNumber());
        txtEmpEmail.setText(empDetailsSelected.getEmpEmail());
        lblImageShowPath.setText(empDetailsSelected.getEmpImage());
        ImageIcon imageDisplay = new ImageIcon (lblImageShowPath.getText());
        Image image = imageDisplay.getImage();
        Image newImage = image.getScaledInstance(230, 170, Image.SCALE_DEFAULT);
        imageDisplay = new ImageIcon(newImage);
        lblImageShow.setIcon(imageDisplay);
    }//GEN-LAST:event_btnViewActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        if(!txtColName.getText().isEmpty() && !txtSearchValue.getText().isEmpty()){
            String colName = txtColName.getText().trim();
            String searchValue = txtSearchValue.getText().trim();
            
            txtColName.setText("");
            txtSearchValue.setText("");
            
            txtEmpFullName.setText("");
            txtEmpId.setText("");
            txtEmpAge.setText("");
            txtEmpGender.setText("");
            txtEmpStartDate.setText("");
            txtEmpLevel.setText("");
            txtEmpTeamInfo.setText("");
            txtEmpPosTitle.setText("");
            txtEmpPhoneNo.setText("");
            txtEmpEmail.setText("");
            lblImageShowPath.setText("");
            lblImageShow.setIcon(null);
//            System.out.println(colName);
//            System.out.println(searchValue);
            DefaultTableModel model = (DefaultTableModel)  tblEmpDetails.getModel();
             model.setRowCount(0);
            ArrayList<HumanResource> searchedList;
            searchedList= history.getEmployeeColumns(colName, searchValue);
            
            if(searchedList.size()>0){
                for(HumanResource hr : searchedList){
                    Object[] row = new Object[10];
                    row[0] = hr;
                    row[1] = hr.getEmpId();
                    row[2] = hr.getEmpAge();
                    row[3] = hr.getEmpGender();
                    row[4] = hr.getEmpStartDate();  
                    row[5] = hr.getEmpLevel();
                    row[6] = hr.getEmpTeamInfo();
                    row[7] = hr.getEmpTitle();
                    row[8] = hr.getEmpPhNumber();
                    row[9] = hr.getEmpEmail();
                    
                    

                    model.addRow(row);
                }
            }else{
                JOptionPane.showMessageDialog(null, "No records found. Please enter text to search!");
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Search textbox cannot be empty. Please enter text to search!");
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnClearDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearDetailsActionPerformed
        // TODO add your handling code here:
        txtEmpFullName.setText("");
        txtEmpId.setText("");
        txtEmpAge.setText("");
        txtEmpGender.setText("");
        txtEmpStartDate.setText("");
        txtEmpLevel.setText("");
        txtEmpTeamInfo.setText("");
        txtEmpPosTitle.setText("");
        txtEmpPhoneNo.setText("");
        txtEmpEmail.setText("");
        lblImageShowPath.setText("");
        lblImageShow.setIcon(null);
    }//GEN-LAST:event_btnClearDetailsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClearDetails;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnView;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblColName;
    private javax.swing.JLabel lblEmpAge;
    private javax.swing.JLabel lblEmpEmail;
    private javax.swing.JLabel lblEmpFullName;
    private javax.swing.JLabel lblEmpGender;
    private javax.swing.JLabel lblEmpId;
    private javax.swing.JLabel lblEmpLevel;
    private javax.swing.JLabel lblEmpPhoneNo;
    private javax.swing.JLabel lblEmpPosTitle;
    private javax.swing.JLabel lblEmpStartDate;
    private javax.swing.JLabel lblEmpTeamInfo;
    private javax.swing.JLabel lblImageShow;
    private javax.swing.JLabel lblImageShowPath;
    private javax.swing.JLabel lblSearchInstr;
    private javax.swing.JLabel lblSearchValue;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblEmpDetails;
    private javax.swing.JTextField txtColName;
    private javax.swing.JTextField txtEmpAge;
    private javax.swing.JTextField txtEmpEmail;
    private javax.swing.JTextField txtEmpFullName;
    private javax.swing.JTextField txtEmpGender;
    private javax.swing.JTextField txtEmpId;
    private javax.swing.JTextField txtEmpLevel;
    private javax.swing.JTextField txtEmpPhoneNo;
    private javax.swing.JTextField txtEmpPosTitle;
    private javax.swing.JTextField txtEmpStartDate;
    private javax.swing.JTextField txtEmpTeamInfo;
    private javax.swing.JTextField txtSearchValue;
    // End of variables declaration//GEN-END:variables
    
    private void readTable() {
        
        DefaultTableModel model = (DefaultTableModel) tblEmpDetails.getModel();
        model.setRowCount(0);
        
        for(HumanResource hr : history.getHistory()){
            
            Object[] row = new Object[5];
            row[0] = hr;
            row[1] = hr.getEmpId();
            row[2] = hr.getEmpTitle();
            row[3] = hr.getEmpPhNumber();
            row[4] = hr.getEmpEmail();

            
            model.addRow(row);
        }
    }
}
